---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-master
  labels:
    name: queue-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: queue-master
  template:
    metadata:
      labels:
        name: queue-master
    spec:
      containers:
      - name: queue-master
        image: novatec/observability-queue-master:0.3.1
        env:
         {{- if .Values.zipkin.enabled }}
         - name: ZIPKIN
           value: {{ .Values.zipkin.url }}
         {{- end }}
         - name: JAVA_OPTS
           value: {{ .Values.java.options }}
         - name: APPLICATIONINSIGHTS_CONNECTION_STRING
           value: "InstrumentationKey=${ .Values.azure.app_insights };IngestionEndpoint=https://westeurope-2.in.applicationinsights.azure.com/"
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 300m
            memory: 1000Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
