on:
  push:
    branches:
    - master
env:
  containerimagetag: ${{ env.Build.SourceVersion }}
  containerregistry: nttcshowcase.azurecr.io
  containerimagerepository: technologyconsulting-showcase-integrationdomain
  containerregistrysericeconnection: acr-sc
jobs:
  build_Stage_getSecrets:
    runs-on: ubuntu-latest
    name: get Secrets and deploy
    steps:
    - uses: actions/checkout@v2
    - uses: azure/cli@v1.0.0
      with:
        inlineScript: az keyvault secret list --subscription Practice-Area-TC-Dev(95352c54-cee5-4d25-a9a1-0857616d97e5) --vault-name vault-tc-showcase-prod
        azcliversion: latest
  build_Stage_dockerbuild:
    runs-on: ubuntu-latest
    name: Docker Build and Push
    steps:
    - uses: actions/checkout@v2
    - # 'Note: No conversion path currently exists for build-push (does it need two tasks in GitHub?)'
      run: docker build-push . --file **/Dockerfile.connect ${{ env.containerregistrysericeconnection }} ${{ env.containerimagerepository }} --tags ${{ env.containerimagetag }} --build-arg CONNECTORS="confluentinc/kafka-connect-jdbc:5.5.0 debezium/debezium-connector-postgresql:1.3.1"
                    
