name: Create Firefighter

on:
  workflow_dispatch:
    inputs:
      firefighterName:
        description: Tell me the hero's name
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set vars and run TF
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
          STATE_BLOBACCESSKEY: ${{ secrets.TC_SHOWCASE_BLOBACCESSKEY }}
          TF_VAR_storage_account_name: 'tcshowcasecommonstorage'
          FIREFIGHTERNAME: ${{ github.event.inputs.firefighterName }}
          TF_VAR_environment: 'test'
          TF_VAR_tfversion: '0.14.2'
          TF_ACTION: 'plan'  
        run: |
          ./createFirefighter.sh
        working-directory: firefighterResources
