name: Build infrastructure

on:
  workflow_dispatch:
    inputs:
      tfAction:
        description: Terraform Action (in lower case) [plan, apply, destroy]
        required: true
        
      tfVersion:
        description: Terraform Version to use (14.0.2, ... )
        required: true
         
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set vars 
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
          STATE_BLOBACCESSKEY: ${{ secrets.TC_SHOWCASE_BLOBACCESSKEY }}
          TF_VAR_storage_account_name: 'tcshowcasecommonstorage'
          TF_VAR_developergroup: ${{ secrets.TC_SHOWCASE_ARM_DEVELOPERGROUP_ID }}
          TF_VAR_spigroup: ${{ secrets.TC_SHOWCASE_ARM_SPIGROUP_ID }}
          TF_VAR_VPC_ADRESS_SPACE: '172.18.1.0/24'
          TF_VAR_environment: 'test'
          TF_VAR_tfversion: '0.14.2'
          TF_ACTION: 'plan'  
        run: |
          TF_VAR_tfversion=${{ github.event.inputs.tfVersion || env.TF_VAR_tfversion }}
          TF_ACTION=${{ github.event.inputs.tfAction || env.TF_ACTION }}
          ./createInfrastructure.sh